Asp.Net Core Mvc/CoreMvcProject/CoreMvcProject/Models/Unit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CoreMvcProject.Models
{
    public class Unit
    {
        [Key]
        public int UnitId { get; set; }
        public string UnitName { get; set; }
        public IList<Personal> Personals { get; set; }
    }
}

Asp.Net Core Mvc/CoreMvcProject/CoreMvcProject/Controllers/UnitController.cs
using CoreMvcProject.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreMvcProject.Controllers
{
    public class UnitController : Controller
    {
        Context context = new Context();
        public IActionResult Index()
        {
            var values = context.Units.ToList();
            return View(values);
        }
        [HttpGet]
        public IActionResult AddUnit()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddUnit(Unit unit)
        {
            context.Units.Add(unit);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult RemoveUnit(int id)
        {
            var unit = context.Units.Find(id);
            context.Units.Remove(unit);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult GetUnit(int id)
        {
            var unit = context.Units.Find(id);
            return View("GetUnit", unit);
        }
        public IActionResult UpdateUnit(Unit unit)
        {
            var un = context.Units.Find(unit.UnitId);
            un.UnitName = unit.UnitName;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult UnitDetail(int id)
        {
            var values = context.Personals.Where(x => x.UnitId == id).ToList();
            var untname = context.Units.Where(x => x.UnitId == id).Select(y => y.UnitName).FirstOrDefault();
            ViewBag.unname = untname;
            return View(values);
        }
    }
}

Asp.Net Core Mvc/CoreMvcProject/CoreMvcProject/Views/Unit/AddUnit.cshtml
@model CoreMvcProject.Models.Unit
@{
    ViewData["Title"] = "AddUnit";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />
<form class="form-group"method="post">
    <b>Birim Adı</b>
    @Html.TextBoxFor(x=>x.UnitName,new { @class="form-control"})
    <br />
    <button class="btn btn-info">Birim Ekle</button>
</form>

Asp.Net Core Mvc/CoreMvcProject/CoreMvcProject/Views/Unit/GetUnit.cshtml
@model CoreMvcProject.Models.Unit
@{
    ViewData["Title"] = "GetUnit";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />
@using (Html.BeginForm("UpdateUnit", "Unit", FormMethod.Post))
{
    <b>Birim Id</b>
    @Html.TextBoxFor(x => x.UnitId, new { @class = "form-control" })
    <br />
    <b>Birim Ad</b>
    @Html.TextBoxFor(x => x.UnitName, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Birim Güncelle</button>
}

Asp.Net Core Mvc/CoreMvcProject/CoreMvcProject/Views/Unit/Index.cshtml
@using CoreMvcProject.Models
@model List<Unit>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>UnitId</th>
        <th>Birim</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.UnitId</td>
            <td>@item.UnitName</td>
            <td><a href="/Unit/RemoveUnit/@item.UnitId" class="btn btn-danger">Sil</a></td>
            <td><a href="/Unit/GetUnit/@item.UnitId" class="btn btn-success">Güncelle</a></td>
            <td><a href="/Unit/UnitDetail/@item.UnitId" class="btn btn-default" style="background-color:#dee61d">Detaylar</a></td>

        </tr>
    }
</table>
<a href="/Unit/AddUnit/" class="btn btn-primary">Yeni Birim Ekle</a>

Asp.Net Core Mvc/CoreMvcProject/CoreMvcProject/Views/Unit/UnitDetail.cshtml
@using CoreMvcProject.Models
@model List<Personal>
@{
    ViewData["Title"] = "UnitDetail";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}
<br />

<br />
<h2>@ViewBag.unname Departmanı</h2>
<br />

<table class="table table-bordered">
    <tr>
        <th>Personel Id</th>
        <th>Personel Ad</th>
        <th>Personel Soyad</th>
        <th>Personel Şehir</th>

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.PersonalId</td>
            <td>@item.PersonalFirstName</td>
            <td>@item.PersonalLastName</td>
            <td>@item.PersonalCity</td>
        </tr>
    }
</table>