Asp.Net Core Mvc/CoreMvcProject/CoreMvcProject/Controllers/MyPersonalController.cs
using CoreMvcProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreMvcProject.Controllers
{
    public class MyPersonalController : Controller
    {
        Context context = new Context();
        [Authorize]
        public IActionResult Index()
        {
            var values = context.Personals.Include(x => x.Unit).ToList();
            return View(values);
        }
        [HttpGet]
        public IActionResult NewPersonal()
        {
            List<SelectListItem> values = (from x in context.Units.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UnitName,
                                               Value = x.UnitId.ToString()
                                           }).ToList();
            ViewBag.val = values;
            return View();
        }
        [HttpPost]
        public IActionResult NewPersonal(Personal personal)
        {
            var per = context.Units.Where(x => x.UnitId == personal.Unit.UnitId).FirstOrDefault();
            personal.Unit = per;
            context.Personals.Add(personal);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult RemovePersonal(int id)
        {
            var per = context.Personals.Find(id);
            context.Personals.Remove(per);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult PersonalGetir(int id)
        {
            List<SelectListItem> values = (from x in context.Units.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UnitName,
                                               Value = x.UnitId.ToString()
                                           }).ToList();
            ViewBag.val = values;
            var perso = context.Personals.Find(id);
            return View("PersonalGetir",perso);
        }
        public IActionResult UpdatePersonal(Personal personal)
        {
            var pers = context.Personals.Find(personal.PersonalId);
            pers.PersonalFirstName = personal.PersonalFirstName;
            //per.PersonalLastName = personal.PersonalLastName;
            //per.PersonalCity = personal.PersonalCity;
            context.SaveChanges();
            return RedirectToAction("Index");
        }

       



    }
}

Asp.Net Core Mvc/CoreMvcProject/CoreMvcProject/Views/MyPersonal/Index.cshtml
@using CoreMvcProject.Models
@model List<Personal>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>Personel Id</th>
        <th>Personel Ad</th>
        <th>Personel Soyad</th>
        <th>Personel Şehir</th>
        <th>Personel Birim</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.PersonalId</td>
            <td>@item.PersonalFirstName</td>
            <td>@item.PersonalLastName</td>
            <td>@item.PersonalCity</td>
            <td>@item.Unit.UnitName</td>
            <td><a href="/MyPersonal/RemovePersonal/@item.PersonalId" class="btn btn-danger">Sil</a></td>
            <td><a href="/MyPersonal/PersonalGetir/@item.PersonalId" class="btn btn-success">Güncelle</a></td>
        </tr>
    }
</table>
<a href="/MyPersonal/NewPersonal/" class="btn btn-primary">Yeni Personel Ekle</a>

Asp.Net Core Mvc/CoreMvcProject/CoreMvcProject/Views/MyPersonal/NewPersonal.cshtml
@model CoreMvcProject.Models.Personal
@{
    ViewData["Title"] = "GetPersonal";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}


<br />
<form class="form-group" method="post">
    <b>Personal Adı</b>
    @Html.TextBoxFor(x => x.PersonalFirstName, new { @class = "form-control" })
    <br />
    <b>Personal Soyadı</b>
    @Html.TextBoxFor(x => x.PersonalLastName, new { @class = "form-control" })
    <br />
    <b>Personel Şehir</b>
    @Html.TextBoxFor(x => x.PersonalCity, new { @class = "form-control" })
    <br />
    <b>Birim</b>
    @Html.DropDownListFor(x => x.Unit.UnitId, (List<SelectListItem>)ViewBag.val, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Personel Ekle</button>
</form>

Asp.Net Core Mvc/CoreMvcProject/CoreMvcProject/Views/MyPersonal/PersonalGetir.cshtml
@model CoreMvcProject.Models.Personal
@{
    ViewData["Title"] = "PersonalGetir";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />
@using (Html.BeginForm("UpdatePersonal", "MyPersonal", FormMethod.Post))
{
    <b>Personel Adı</b>
    @Html.TextBoxFor(x => x.PersonalFirstName, new { @class = "form-control" })
    <br />
    <b>Personel Soyad</b>
    @Html.TextBoxFor(x => x.PersonalLastName, new { @class = "form-control" })
    <br />
    <b>Personel Şehir</b>
    @Html.TextBoxFor(x => x.PersonalCity, new { @class = "form-control" })
    <br />
    <b>Birim</b>
    @Html.DropDownListFor(x => x.Unit.UnitId, (List<SelectListItem>)ViewBag.val, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Personel Güncelle</button>

}